name: cppcheck-action-test

on:
  workflow_run:
    workflows: ["pr-build"]
    types:
      - completed

permissions:
  pull-requests: write
  contents: read
  
jobs:
  build:
    name: cppcheck-test
    runs-on: self-hosted
    steps:
      - name: Clean workspace
        run: |
          sudo rm -rf ${{ github.workspace }}/*
          sudo rm -rf ${{ github.workspace }}/.??* 
      - uses: actions/checkout@v2
      - name: Run cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GH_TOKEN }}
        # Save cppcheck output to a file
        continue-on-error: true
        id: cppcheck
      - name: Ensure workspace is writable
        run: sudo chmod -R ugo+w ${{ github.workspace }}
      # Save the cppcheck output (assuming it outputs to cppcheck_report.txt)
      - name: "Pull Docker image for amd64"
        if: steps.changes.outputs.docker != 'true' && steps.changes.outputs.version != 'true'
        run: |
          docker pull harbor.elementosystems.com/pico_webapp/picowwebusb:v${{ env.VERSION }}-amd64
      - name: Run cppcheck on source code
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" harbor.elementosystems.com/picow_usb/picowwebusb:v${{ env.VERSION }}-amd64 \
          cppcheck --enable=all --inconclusive --std=c++17 /src 2> cppcheck_report.txt
      - name: Comment PR with cppcheck report
        if: github.event.workflow_run.conclusion == 'success'
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: cppcheck_report.txt
          comment_tag: cppcheck-report
          github_token: ${{ secrets.GITHUB_TOKEN }}

