name: Build PicoWWebUSB

on:
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    runs-on: ["self-hosted", "Linux", "X64"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: "Verify version consistency"
        run: |
          # Extract version from version.json and store it in VERSION
          VERSION=$(jq -r '.version' version.json)

      - name: "Build Docker image for arm64"
        run: |
            docker buildx build \
            --platform linux/amd64 \
            -t harbor.elementosystems.com/picow_usb/PicoWWebUSB:v${{ env.VERSION }}-amd64 \
            --load \
            .

      - name: Build project in container
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" pico-build bash -c "mkdir -p build && cd build && cmake -DPICO_SDK_PATH=/root/.pico-sdk -G Ninja .. && ninja"
