name: Build PicoWWebUSB Docker Images

on:
  pull_request:
    branches: [ main, development ]
jobs:
  build:
    runs-on: ["self-hosted", "Linux", "X64"]
    steps:
      - name: Clean workspace
        run: |
          sudo rm -rf ${{ github.workspace }}/*
          sudo rm -rf ${{ github.workspace }}/.??*      
      - name: Checkout code
        uses: actions/checkout@v3   
      - name: Filter changed files
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            docker:
              - 'Dockerfile'
            version:
              - 'version.json' 
      - name: Verify version consistency
        id: get_version
        run: |
          # Extract version from version.json and store it in VERSION
          VERSION=$(jq -r '.version' version.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: "Build Docker image for amd64"
        if: steps.changes.outputs.docker == 'true' || steps.changes.outputs.version == 'true'
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t harbor.elementosystems.com/pico_webapp/picowwebusb:v${{ env.VERSION }}-amd64 \
            --load \
            .
      - name: "Pull Docker image for amd64"
        if: steps.changes.outputs.docker != 'true' && steps.changes.outputs.version != 'true'
        run: |
          docker pull harbor.elementosystems.com/pico_webapp/picowwebusb:v${{ env.VERSION }}-amd64
      - name: Build project in container
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" harbor.elementosystems.com/picow_usb/picowwebusb:v${{ env.VERSION }}-amd64 bash -c "mkdir -p build && cd build && cmake -DPICO_SDK_PATH=/root/.pico-sdk -G Ninja .. && ninja"
